### ISSUE TITLE
Default ports in worker/web-server are ignored

### ISSUE THREAD

**Issue by msn-resy** [TonicAI/tonic_helm_charts#94]
When running the helm chart in "unprivileged" mode, if no port information is passed the default port is still set to 443 from TONIC_HTTPS_PORT and TONIC_WEOKER_HEALTH_PORT_HTTPS, being in unprivileged mode port 443 is not allowed and fails. 

Also the port in template is ignore completely due to the env var.

**Comment by anr-tonic** [comment]
> Also the port in template is ignore completely due to the env var.

Could you provide some more details here? I am able to reproduce the unprivileged still setting 443 for https (and 80 for http) --  this is due to [default values in the web and worker configuration](https://github.com/TonicAI/tonic_helm_charts/blob/39138b90316fd6430347a7abe6c6d9d0effa120d/values.sample.yaml#L72) but I am able to override these values explicitly:

```yaml
#values.local.yaml
tonicai:
  web_server:
    ports:
        https: 10443
```

And when templating:
```
$ helm template -f values.sample.yaml -f values.local.yaml  \
     -s templates/tonic-web-server-deployment.yaml  . | grep -C 2 10443
          value: https://tonic-pyml-service:7700
        - name: TONIC_PORT_HTTPS
          value: "10443"
        - name: TONIC_HTTPS_ONLY
          value: "true"
--
        name: tonic-web-server
        ports:
        - containerPort: 10443
          name: "https"
        resources:
--
            scheme: HTTPS
            path: /health
            port: 10443
          initialDelaySeconds: 5
          periodSeconds: 60
```
